updated dev
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  buildandDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Connect to Lab machine for tomcat 9
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
       host: 'mittalsonal04gmsl0045.simplilearnlabs.com'
       user: 'mittalsonal04gm'
       pass: 'al04gm0A@ad34w'
       port: 42006
       connect_timeout: 10s
       first_ssh: |
          sudo chmod 777 /var/lib/tomcat9/webapps
       scp: |
         './target/*.jar' => /var/lib/tomcat9/webapps
       last_ssh: |
          ls -al 
          sudo systemctl restart tomcat9 
